### ISSUE TITLE
Error: HttpException Invalid statusCode 206

### ISSUE THREAD

**Issue by lucasfcardozo** [OutdatedGuy/cached_video_player_plus#53]
My code:

```dart
final url = "https://domain.com/..../..../video.mp4";
final _videoController = CachedVideoPlayerPlusController.networkUrl(
  Uri.parse(url),
  httpHeaders: {
    'Range': 'bytes=0-4999',
  }
);
```
```
E/flutter (22082): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HttpException: 
Invalid statusCode: 206, uri = https://domain.com/..../..../video.mp4
E/flutter (22082): #0      WebHelper._manageResponse (package:flutter_cache_manager/src/web/web_helper.dart:123:7)
E/flutter (22082): <asynchronous suspension>
E/flutter (22082): #1      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:97:5)
E/flutter (22082): <asynchronous suspension>
E/flutter (22082): #2      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:64:7)
E/flutter (22082): <asynchronous suspension>```

Even with this error, the video plays. 

The question is: will the rest of the video be downloaded progressively? Or is it fully downloaded?

**Comment by OutdatedGuy** [comment]
Looks like the video downloading has failed due to the `Range` header passed in `httpHeaders`. The `httpHeaders` are also passed to a separate mechanism that handles video download, and looks like such a header is not supported for that.

I'll add a param to set if `httpHeaders` should be used to download the video as well in a later update.
